[package]
name = "hello-dwrite"
version = "0.1.0"
edition = "2021"

[dependencies]
png = "0.17"

[dependencies.windows]
version = "0.59"
features = [
    "Win32_Foundation",
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Direct2D",
]
